-
  name: Setup dev1
  hosts: localhost
  tasks:
    - name: install python lib
      shell: "apt install python3-pip -y && pip install docker"

    - name: install community docker
      shell: "ansible-galaxy collection install community.docker"

    - name: create ssh key
      shell: "ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -N ''"

-
  name: Setup dev2
  hosts: dev2
  vars_files:
    - ./vars.yml
  tasks:
    - name: ssh_auth
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"

    - name: add user
      user:
        name: DevOps
        password: $6$e/MH37X8xX5q1MQP$ePQIcono8nFKAizicF4.zkrCnP0m4roXcJVtNi0ef9qMp.7ZBRWSHhciwexk97KNyrGCdR5c9.qvBrN8yvxWx1
        shell: /bin/bash
        groups:
          - 'sudo'

    - name: make dir
      shell: "mkdir /home/DevOps/.ssh" 

    - name: copy ssh key
      copy:
        src: "/root/.ssh/id_rsa.pub"
        dest: "/home/DevOps/.ssh/dev_1_key"
        owner: DevOps
        group: DevOps
        mode: '0644'

    - name: add line 1 sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: "PubkeyAuthentication yes"

    - name: add line 2 sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: "AuthorizedKeysFile     .ssh/dev_1_key"

    - name: sudo nopass
      lineinfile:
        dest: /etc/sudoers
        line: "DevOps ALL=(ALL) NOPASSWD: ALL"

    - name: restart sshd
      service:
        name: sshd
        state: restarted

    - name: install docker
      script: "./install_docker.sh"

    - name: install python lib
      shell: "apt install python3-pip -y && pip install docker"

    - name: start docker
      service:
        name: docker
        state: started

    - name: start db container
      docker_container:
        name: db
        state: started
        recreate: yes
        restart_policy: always
        detach: yes
        env:
          POSTGRES_PASSWORD: 1qw2
        published_ports:
          - "5432:5432"
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        image: postgres:15.2-alpine3.17
      register: postgres_container

    - name: cp sql file
      copy:
        src: ./postgres.sql
        dest: /tmp/postgres.sql

    - name: create pgpass
      shell: "echo 'localhost:5432:*:postgres:1qw2' > ~/.pgpass && chmod 600 ~/.pgpass"

    - name: install psql dev2
      shell: "apt install postgresql-client-12 -y"

    - name: set db
      shell: "psql -h localhost -U postgres -f /tmp/postgres.sql"

    - name: copy file pg_hba to host
      copy:
        src: ./pg_hba.conf
        dest: /root/pg_hba.conf

    - name: add line
      lineinfile:
        dest: /root/pg_hba.conf
        line: "host     all     developer     {{ip_dev2}}/32     password"

    - name: copy file pg_hba to container
      shell: "docker cp ./pg_hba.conf db:/var/lib/postgresql/data/pg_hba.conf"

-
  name: Setup dev3
  hosts: dev3
  vars_files:
    - ./vars.yml
  tasks:
    - name: install psql dev3 
      shell: "apt update && apt install postgresql-client-12 -y"

    - name: install python lib
      shell: "apt install python3-pip -y && pip install psycopg2-binary"

    - name: Test db connection
      postgresql_ping:
        login_host: '{{ip_dev2}}'
        login_user: developer
        login_password: 1qw2
